main:
    path: /
    controller: App\Controller\PageContentController::main

service:
    path: /service
    controller: App\Controller\PageContentController::service

contact:
    path: /contact
    controller: App\Controller\PageContentController::contact

products:
    path: /products
    controller: App\Controller\ProductsController::showProducts

product:
    path: /products/{id}
    controller: App\Controller\ProductsController::showProduct

category:
    path: /products-category/{categoryId}
    controller: App\Controller\ProductsController::showProductsCategory

blog:
    path: /blog
    controller: App\Controller\BlogController::index

article:
    path: /blog/{id}
    controller: App\Controller\BlogController::showArticle

createArticle:
    path: /article/create
    controller: App\Controller\BlogController::createArticle

updateArticle:
    path: /article/update/{article}
    controller: App\Controller\BlogController::updateArticle

deleteArticle:
    path: /article/delete/{article}
    controller: App\Controller\BlogController::deleteArticle